requires 'Cache';
requires 'DateTime';
requires 'DateTime::Format::Strptime';
requires 'File::Slurp';
requires 'GIS::Distance';
requires 'GIS::Distance::Fast';
requires 'JSON';
requires 'JSON::XS';
requires 'LWP::UserAgent';
requires 'LWP::Protocol::https';
requires 'Mojolicious';
requires 'Travel::Status::DE::DBWagenreihung', '0.06';
requires 'Travel::Status::DE::IRIS', '1.57';
requires 'XML::LibXML';
