#!/usr/bin/env perl
# Copyright (C) 2020 Daniel Friesel
#
# SPDX-License-Identifier: CC0-1.0

use strict;
use warnings;
use 5.020;

use JSON;
use File::Slurp qw(write_file);
use Travel::Status::DE::IRIS::Stations;

my @station_names = map { $_->[1] } Travel::Status::DE::IRIS::Stations::get_stations();

my $station_json = JSON->new->utf8->encode([@station_names]);

my $autocomplete = <<"EOF";
\$(function() {
	var stations = $station_json;
	\$('input.station').autocomplete({
		delay: 0,
		minLength: 3,
		source: stations
	});
});
EOF

write_file("public/static/js/autocomplete.js", $autocomplete);
